# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="(i.e. 'Josiah home-page' or 'patron_api')", max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('response_expected', models.PositiveIntegerField(blank=True, editable=False, help_text="for if you want to test the response code, like '200' ('OK')", null=True)),
                ('text_expected', models.TextField(blank=True, null=True)),
                ('check_frequency_number', models.PositiveIntegerField(blank=True, help_text='(More-frequent checks increase server load)', null=True)),
                ('check_frequency_unit', models.CharField(blank=True, choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month')], default='hour', max_length=10, null=True)),
                ('calculated_seconds', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('email_addresses', models.TextField(blank=True, help_text='(Separate multiple email-addresses with a comma, like aaa@example.com, bbb@example.com)', null=True)),
                ('email_message', models.TextField(blank=True, help_text='(Will be included in body of email)', null=True)),
                ('recent_checked_time', models.DateTimeField(blank=True, help_text='(Set automatically)', null=True)),
                ('recent_checked_result', models.CharField(blank=True, help_text='(Set automatically)', max_length=50, null=True)),
                ('previous_checked_result', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('pre_previous_checked_result', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('next_check_time', models.DateTimeField(blank=True, help_text='(Set automatically)', null=True)),
            ],
            options={
                'verbose_name_plural': 'CheckSite Entries',
                'ordering': ['name'],
            },
        ),
    ]
