# -*- coding: utf-8 -*-

import json, os


README_URL = os.environ['SITECHKR__README_URL']

DEFAULT_RECHECK_MINUTES = int( os.environ['SITECHKR__DEFAULT_RECHECK_MINUTES'] )

EMAIL_FROM_URL = os.environ['SITECHKR__EMAIL_FROM_URL']

TEST_EMAIL = os.environ['SITECHKR__TEST_EMAIL']
TEST_SITE_URL_GOOD_HTML = os.environ['SITECHKR__TEST_SITE_URL_GOOD_HTML']
TEST_SITE_URL_TO_FUNKY_PDF = os.environ['SITECHKR__TEST_SITE_URL_TO_FUNKY_PDF']
